### ISSUE TITLE
why not work?

### ISSUE THREAD

**Issue by Jing-Heng-Zhang** [othree/javascript-libraries-syntax.vim#28]
why not work after git clone  git clone https://github.com/othree/javascript-libraries-syntax.vim.git ~/.vim/bundle/javascript-libraries-syntax.vim

**Comment by othree** [comment]
You didn't provide enough information

**Comment by Jing-Heng-Zhang** [comment]
I install your source to bundle with pathogen,nothing happened
Other plugins I did this works

if I did wrong,could you please send me the right way to install with pathogen step by step
thanks in advance

**Comment by othree** [comment]
There are only three lib is on by default: `jquery,underscore,backbone`
If you are writing codes use other lib.
You need to do more config.

https://github.com/othree/javascript-libraries-syntax.vim#config
