### ISSUE TITLE
Ramda support

### ISSUE THREAD

**Issue by sotojuan** [othree/javascript-libraries-syntax.vim#34]
Support for [ramda](https://github.com/ramda/ramda) would be great. I don't know anything about vim syntax coloring, otherwise I'd help (might look into it though). However, it should be very similar to lodash—if not exactly the same.

**Comment by othree** [comment]
[Here](https://github.com/othree/javascript-libraries-syntax.vim/issues/27#issuecomment-72313316) are some infos about what you can help.

**Comment by Shou** [comment]
The global variable in Ramda is `R`. Here are the functions by category:

Function
__ addIndex always ap apply applySpec binary bind call comparator compose composeK composeP construct constructN converge curry curryN empty F flip identity invoker juxt lift liftN memoize nAry nthArg of once partial partialRight pipe pipeK pipeP T tap tryCatch unapply unary uncurryN useWith wrap 

Math
add dec divide inc mathMod mean median modulo multiply negate product subtract sum

List
adjust all allUniq any aperture append chain concat contains drop dropLast dropLastWhile dropRepeats dropRepeatsWith dropWhile filter find findIndex findLast findLastIndex flatten forEach fromPairs groupBy groupWith head indexBy indexOf init insert insertAll intersperse into join last lastIndexOf length map mapAccum mapAccumRight mergeAll none nth pair partition pluck prepend range reduce reduceBy reduced reduceRight reject remove repeat reverse scan sequence slice sort splitAt splitEvery splitWhen tail take takeLast takeLastWhile takeWhile times transduce transpose traverse unfold uniq uniqBy uniqWith unnest update without xprod zip zipObj zipWith

Logic
allPass and anyPass both complement cond defaultTo either ifElse isEmpty not or pathSatisfies propSatisfies unless until when

Object
assoc assocPath clone dissoc dissocPath eqProps evolve has hasIn invert invertObj keys keysIn lens lensIndex lensPath lensProp mapObjIndexed merge mergeWith mergeWithKey objOf omit over path pathOr pick pickAll pickBy project prop propOr props set toPairs toPairsIn values valuesIn view where whereEq

Relation
clamp countBy difference differenceWith eqBy equals gt gte identical intersection intersectionWith lt lte max maxBy min minBy pathEq propEq sortBy symmetricDifference symmetricDifferenceWith union unionWith

Type
is isArrayLike isNil propIs type

String
match replace split test toLower toString toUpper trim


Hope this helps!

**Comment by othree** [comment]
Great, I will take some time to complete this~

**Comment by othree** [comment]
I will assume this is `0.21.0`

**Comment by Shou** [comment]
Yeah it's from `0.21.0`

**Comment by othree** [comment]
@Shou First reversion to support Ramda is ready, could you take a try to see is there any issue?

**Comment by Shou** [comment]
Can confirm that it works with 13f752fc7c0ba933c622bc462a924d14d5348530!

**Comment by sotojuan** [comment]
Can we close this now then? @Shou

**Comment by Shou** [comment]
Yup, it's been working fine here.
