### ISSUE TITLE
Can't update to c2f17e2..13f752f

### ISSUE THREAD

**Issue by yifanchen** [othree/javascript-libraries-syntax.vim#52]
I can't update `c2f17e2..13f752f`, it's been few weeks. I am on Neovim.

**Comment by othree** [comment]
Maybe you can try reinstall it?

**Comment by yifanchen** [comment]
Tried thousand times already.

**Comment by othree** [comment]
I mean, reinstall javascript-libraries-syntax.vim.

**Comment by yifanchen** [comment]
I believe I have tried, let me try it again.

**Comment by yifanchen** [comment]
that worked. Thanks.
