### ISSUE TITLE
Omnicomplete Not Working in HTML Files

### ISSUE THREAD

**Issue by bgx90** [othree/javascript-libraries-syntax.vim#62]
After installing othree/javascript-libraries-syntax.vim
via pathogen, I am not able to get omnicomplete to recognize ng directives (ng-controller, etc.) in html files.  Syntax highlighting works when I type out the entire name of a directive, but typing `ng-` and then `Ctrl-X Ctrl-O` results in no pattern being matched by omnicomplete.  I am using Vim version 8.0.494 running in Cygwin through ConEmu.  The SyntaxComplete plugin is included in this version of Vim.  I have no other syntax highlighting plugins installed.  I used the command `:syntax` to verify that the syntax highlighting rules in the plugin's angularjs.html.vim file were in place.  I used the command `:set omnifunc?` to verify that `omnifunc=htmlcomplete#CompleteTags`.

**Comment by othree** [comment]
Sorry, this is syntax highlight only script.
Not adding any candidate to omnicomplete.

**Comment by bgx90** [comment]
Thank you for your reply.  I am aware that othree/javascript-libraries-syntax.vim is a syntax highlighting plugin, but your README for this plugin says, "SyntaxComplete also works well on all supported languages."  This does not seem to be the case concerning HTML files containing Angular directives when using the version of SyntaxComplete included with Vim 8.0.494.  It appears that the file angularjs.html.vim is not compatible with SyntaxComplete as your README suggests.  Maybe it has something to do with the group names used in the file.  I am not that familiar with Vim syntax highlighting definitions, so I can not say.  I notice that the todo section of the README says "Support future version of SyntaxComplete".  Maybe this refers to the version currently included with Vim?

**Comment by othree** [comment]
SyntaxComplete is not the default complete function for HTML.
[htmlcomplete](https://github.com/vim/vim/blob/master/runtime/autoload/htmlcomplete.vim) is the one for HTML.
You can try force it by:

    setlocal omnifunc=syntaxcomplete#Complete

If you want both working together.
You will need other helper scripts.
I am using https://github.com/othree/vim-autocomplpop
But I think people have other choice.

**Comment by bgx90** [comment]
Thank you for helping me to clear up my confusion.  I see now that `omnifunc` was not set to the correct function.  To use both the `htmlcomplete#CompleteTags` and `syntaxcomplete#Complete` functions, my solution is to leave `omnifunc` set to `htmlcomplete#CompleteTags` as automatically set by the filetype plugin and set `completefunc` to `syntaxcomplete#Complete`.  With this setup, I can use `Ctrl-X Ctrl-O` to get completion options from the html omnicompletion script, and  I can use `Ctrl-X Ctrl-U` to get completion options from the SyntaxComplete plugin which will include the Angular directives from the javascript-libraries-syntax.vim plugin.
